name: Build & Deploy
on:
  push:
    branches:
      - master
    tags:
      - v*
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - run: npm ci

    - run: npm run get:o
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ID: ${{ secrets.GITHUB_ID }}
        SECRET: ${{ secrets.GITHUB_SECRET }}

    - run: npm run get
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ID: ${{ secrets.GITHUB_ID }}
        SECRET: ${{ secrets.GITHUB_SECRET }}

    - run: npm run start
    - run: mkdir -p web/data
    - run: cp -rf dist/* web/data
    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web